- hosts: all
  become: yes
  become_user: root
  become_method: su
  tasks:

   -  name: Installing zabbix-agent on sisal server
      shell: rpm -Uvh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
      args: 
        executable: /bin/bash


   -  name: install zabbix agent using yum
      yum:
        name: zabbix-agent
        state: present


   -  name: start zabbix service
      service:
         name: zabbix-agent
         state: started
         enabled: yes

   -  name: make changes in file
      lineinfile:
           path: /etc/zabbix/zabbix_agentd.conf
           regexp: '{{item.From}}'
           line: '{{item.To}}'
      with_items:
         - { From: '^Server=', To: 'Server='}
         - { From: '^ServerActive=', To: 'ServerActive='}
